# Generated by Django 5.2.5 on 2026-06-26 23:06

import django.db.models.deletion
from django.db import migrations, models


def seed_trade_categories(apps, schema_editor):
    TradeCategory = apps.get_model('workers', 'TradeCategory')
    Service = apps.get_model('workers', 'Service')
    Job = apps.get_model('workers', 'Job')

    category_map = {
        'home-services': {
            'name': 'Home Services',
            'sort_order': 10,
            'children': [
                ('plumbing', 'Plumbing'),
                ('electrical', 'Electrical'),
                ('carpentry', 'Carpentry'),
                ('painting', 'Painting'),
                ('masonry', 'Masonry'),
                ('gardening', 'Gardening'),
                ('cleaning', 'Cleaning'),
                ('roofing', 'Roofing'),
            ],
        },
        'beauty': {
            'name': 'Beauty',
            'sort_order': 20,
            'children': [
                ('hair-styling', 'Hair Styling'),
                ('barbering', 'Barbering'),
                ('makeup', 'Makeup'),
                ('nail-care', 'Nail Care'),
                ('spa-therapy', 'Spa Therapy'),
            ],
        },
        'healthcare': {
            'name': 'Healthcare',
            'sort_order': 30,
            'children': [
                ('home-nursing', 'Home Nursing'),
                ('caregiving', 'Caregiving'),
                ('physiotherapy', 'Physiotherapy'),
                ('medical-lab-support', 'Medical Lab Support'),
                ('wellness-coaching', 'Wellness Coaching'),
            ],
        },
        'engineering': {
            'name': 'Engineering',
            'sort_order': 40,
            'children': [
                ('civil-engineering', 'Civil Engineering'),
                ('mechanical-engineering', 'Mechanical Engineering'),
                ('electrical-engineering', 'Electrical Engineering'),
                ('cad-design', 'CAD Design'),
                ('project-supervision', 'Project Supervision'),
            ],
        },
        'business-services': {
            'name': 'Business Services',
            'sort_order': 50,
            'children': [
                ('accounting', 'Accounting'),
                ('legal-support', 'Legal Support'),
                ('marketing', 'Marketing'),
                ('administration', 'Administration'),
                ('it-support', 'IT Support'),
            ],
        },
    }

    child_lookup = {}
    for trade_slug, trade_data in category_map.items():
        parent, _ = TradeCategory.objects.get_or_create(
            slug=trade_slug,
            defaults={
                'name': trade_data['name'],
                'sort_order': trade_data['sort_order'],
                'is_active': True,
            },
        )
        for position, (child_slug, child_name) in enumerate(trade_data['children'], start=1):
            child, _ = TradeCategory.objects.get_or_create(
                slug=child_slug,
                defaults={
                    'name': child_name,
                    'parent': parent,
                    'sort_order': position,
                    'is_active': True,
                },
            )
            child_lookup[child_slug] = child

    for service in Service.objects.all():
        category_ref = child_lookup.get(service.category)
        if category_ref:
            service.category_ref_id = category_ref.id
            service.save(update_fields=['category_ref'])

    for job in Job.objects.all():
        category_ref = child_lookup.get(job.category)
        if category_ref:
            job.category_ref_id = category_ref.id
            job.save(update_fields=['category_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_alter_notification_notification_type_rfq_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workers.tradecategory')),
            ],
            options={
                'verbose_name_plural': 'Trade categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='workers.tradecategory'),
        ),
        migrations.AddField(
            model_name='service',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='workers.tradecategory'),
        ),
        migrations.RunPython(seed_trade_categories, migrations.RunPython.noop),
    ]
