# Generated by Django 5.2.5 on 2026-06-27 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_african_countries(apps, schema_editor):
    Country = apps.get_model('workers', 'Country')
    User = apps.get_model('workers', 'User')

    countries = [
        ('DZ', 'Algeria', 'DZD', 'Algerian Dinar', 'د.ج', '+213'),
        ('AO', 'Angola', 'AOA', 'Angolan Kwanza', 'Kz', '+244'),
        ('BJ', 'Benin', 'XOF', 'West African CFA Franc', 'CFA', '+229'),
        ('BW', 'Botswana', 'BWP', 'Botswana Pula', 'P', '+267'),
        ('BF', 'Burkina Faso', 'XOF', 'West African CFA Franc', 'CFA', '+226'),
        ('BI', 'Burundi', 'BIF', 'Burundian Franc', 'FBu', '+257'),
        ('CV', 'Cabo Verde', 'CVE', 'Cape Verdean Escudo', '$', '+238'),
        ('CM', 'Cameroon', 'XAF', 'Central African CFA Franc', 'FCFA', '+237'),
        ('CF', 'Central African Republic', 'XAF', 'Central African CFA Franc', 'FCFA', '+236'),
        ('TD', 'Chad', 'XAF', 'Central African CFA Franc', 'FCFA', '+235'),
        ('KM', 'Comoros', 'KMF', 'Comorian Franc', 'CF', '+269'),
        ('CD', 'Democratic Republic of the Congo', 'CDF', 'Congolese Franc', 'FC', '+243'),
        ('CG', 'Republic of the Congo', 'XAF', 'Central African CFA Franc', 'FCFA', '+242'),
        ('CI', "Cote d'Ivoire", 'XOF', 'West African CFA Franc', 'CFA', '+225'),
        ('DJ', 'Djibouti', 'DJF', 'Djiboutian Franc', 'Fdj', '+253'),
        ('EG', 'Egypt', 'EGP', 'Egyptian Pound', 'E£', '+20'),
        ('GQ', 'Equatorial Guinea', 'XAF', 'Central African CFA Franc', 'FCFA', '+240'),
        ('ER', 'Eritrea', 'ERN', 'Eritrean Nakfa', 'Nfk', '+291'),
        ('SZ', 'Eswatini', 'SZL', 'Swazi Lilangeni', 'E', '+268'),
        ('ET', 'Ethiopia', 'ETB', 'Ethiopian Birr', 'Br', '+251'),
        ('GA', 'Gabon', 'XAF', 'Central African CFA Franc', 'FCFA', '+241'),
        ('GM', 'Gambia', 'GMD', 'Gambian Dalasi', 'D', '+220'),
        ('GH', 'Ghana', 'GHS', 'Ghanaian Cedi', 'GH₵', '+233'),
        ('GN', 'Guinea', 'GNF', 'Guinean Franc', 'FG', '+224'),
        ('GW', 'Guinea-Bissau', 'XOF', 'West African CFA Franc', 'CFA', '+245'),
        ('KE', 'Kenya', 'KES', 'Kenyan Shilling', 'KSh', '+254'),
        ('LS', 'Lesotho', 'LSL', 'Lesotho Loti', 'L', '+266'),
        ('LR', 'Liberia', 'LRD', 'Liberian Dollar', 'L$', '+231'),
        ('LY', 'Libya', 'LYD', 'Libyan Dinar', 'LD', '+218'),
        ('MG', 'Madagascar', 'MGA', 'Malagasy Ariary', 'Ar', '+261'),
        ('MW', 'Malawi', 'MWK', 'Malawian Kwacha', 'MK', '+265'),
        ('ML', 'Mali', 'XOF', 'West African CFA Franc', 'CFA', '+223'),
        ('MR', 'Mauritania', 'MRU', 'Mauritanian Ouguiya', 'UM', '+222'),
        ('MU', 'Mauritius', 'MUR', 'Mauritian Rupee', '₨', '+230'),
        ('MA', 'Morocco', 'MAD', 'Moroccan Dirham', 'MAD', '+212'),
        ('MZ', 'Mozambique', 'MZN', 'Mozambican Metical', 'MT', '+258'),
        ('NA', 'Namibia', 'NAD', 'Namibian Dollar', 'N$', '+264'),
        ('NE', 'Niger', 'XOF', 'West African CFA Franc', 'CFA', '+227'),
        ('NG', 'Nigeria', 'NGN', 'Nigerian Naira', '₦', '+234'),
        ('RW', 'Rwanda', 'RWF', 'Rwandan Franc', 'FRw', '+250'),
        ('ST', 'Sao Tome and Principe', 'STN', 'Sao Tome and Principe Dobra', 'Db', '+239'),
        ('SN', 'Senegal', 'XOF', 'West African CFA Franc', 'CFA', '+221'),
        ('SC', 'Seychelles', 'SCR', 'Seychellois Rupee', '₨', '+248'),
        ('SL', 'Sierra Leone', 'SLE', 'Sierra Leonean Leone', 'Le', '+232'),
        ('SO', 'Somalia', 'SOS', 'Somali Shilling', 'Sh', '+252'),
        ('ZA', 'South Africa', 'ZAR', 'South African Rand', 'R', '+27'),
        ('SS', 'South Sudan', 'SSP', 'South Sudanese Pound', '£', '+211'),
        ('SD', 'Sudan', 'SDG', 'Sudanese Pound', '£', '+249'),
        ('TZ', 'Tanzania', 'TZS', 'Tanzanian Shilling', 'TSh', '+255'),
        ('TG', 'Togo', 'XOF', 'West African CFA Franc', 'CFA', '+228'),
        ('TN', 'Tunisia', 'TND', 'Tunisian Dinar', 'DT', '+216'),
        ('UG', 'Uganda', 'UGX', 'Ugandan Shilling', 'USh', '+256'),
        ('ZM', 'Zambia', 'ZMW', 'Zambian Kwacha', 'ZK', '+260'),
        ('ZW', 'Zimbabwe', 'USD', 'United States Dollar', '$', '+263'),
    ]

    for code, name, currency_code, currency_name, currency_symbol, phone_code in countries:
        Country.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'currency_code': currency_code,
                'currency_name': currency_name,
                'currency_symbol': currency_symbol,
                'phone_code': phone_code,
                'is_active': True,
            },
        )

    default_country = Country.objects.filter(code='ZW').first()
    if default_country:
        User.objects.filter(country__isnull=True).update(country=default_country)
    User.objects.filter(verification_status='pending').update(verification_status='approved')


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_job_category_alter_service_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('currency_code', models.CharField(max_length=10)),
                ('currency_name', models.CharField(max_length=120)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('phone_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='company_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='vat_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_document',
            field=models.FileField(blank=True, upload_to='verification_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workers.country'),
        ),
        migrations.RunPython(seed_african_countries, migrations.RunPython.noop),
    ]
