# Generated by Django 5.2.5 on 2026-06-27 00:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_country_user_account_type_user_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('client_scope', models.TextField(help_text='What the client expects in this phase.')),
                ('provider_plan', models.TextField(blank=True)),
                ('provider_notes', models.TextField(blank=True)),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('plan_status', models.CharField(choices=[('draft', 'Draft'), ('pending_client_approval', 'Pending Client Approval'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested')], default='draft', max_length=30)),
                ('execution_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted For Review'), ('approved', 'Approved'), ('disputed', 'Disputed')], default='not_started', max_length=30)),
                ('fund_release_status', models.CharField(choices=[('locked', 'Locked'), ('pending_release', 'Pending Release'), ('released', 'Released'), ('held', 'Held')], default='locked', max_length=30)),
                ('provider_evidence_image', models.FileField(blank=True, upload_to='project_phase_evidence/')),
                ('provider_evidence_notes', models.TextField(blank=True)),
                ('client_approval_signature', models.CharField(blank=True, max_length=200)),
                ('provider_submission_signature', models.CharField(blank=True, max_length=200)),
                ('provider_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'Message'), ('bid', 'Bid'), ('status_change', 'Status Change'), ('review', 'Review'), ('rfq', 'RFQ'), ('invoice', 'Invoice'), ('dispute', 'Dispute')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('customer_definition', models.TextField()),
                ('provider_execution_plan', models.TextField(blank=True)),
                ('provider_description', models.TextField(blank=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('client_defined', 'Client Defined'), ('planned', 'Planned By Provider'), ('approved_to_start', 'Approved To Start'), ('in_progress', 'In Progress'), ('submitted', 'Submitted For Review'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='client_defined', max_length=30)),
                ('client_plan_signature', models.CharField(blank=True, max_length=200)),
                ('client_completion_signature', models.CharField(blank=True, max_length=200)),
                ('provider_updated_at', models.DateTimeField(blank=True, null=True)),
                ('client_approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workers.projectphase')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_client_approval', 'Pending Client Approval'), ('active', 'Active'), ('in_review', 'In Review'), ('disputed', 'Disputed'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('client_signature', models.CharField(blank=True, max_length=200)),
                ('provider_signature', models.CharField(blank=True, max_length=200)),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_signed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_trackers_owned', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_tracker', to='workers.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_trackers_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='projectphase',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='workers.projecttracker'),
        ),
        migrations.CreateModel(
            name='ProjectDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('admin_resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_disputes_resolved', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='workers.projectphase')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='workers.projecttask')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='workers.projecttracker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
