# Generated by Django 5.2.5 on 2026-06-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_projectphase_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectphase',
            name='payment_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='payment_acknowledgement_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='payment_acknowledgement_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='payment_proof_file',
            field=models.FileField(blank=True, upload_to='project_phase_payment_proofs/'),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='payment_proof_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='payment_proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='fund_release_status',
            field=models.CharField(choices=[('locked', 'Locked'), ('pending_release', 'Pending Release'), ('payment_submitted', 'Payment Proof Submitted'), ('released', 'Released'), ('held', 'Held')], default='locked', max_length=30),
        ),
    ]
